name: Build Release
on:
  workflow_dispatch:
  push:
    tags:
      - '*'
    branches:
      - release # temp for testing

jobs:
  build-linux:
    name: Build - AppImage Linux
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'yarn'
          cache-dependency-path: '**/yarn.lock'
      - name: Build Release Executable
        run: |
          yarn install --frozen-lockfile
          yarn --cwd=electron install --frozen-lockfile
          touch .env.local
          yarn release:electron
      - uses: actions/upload-artifact@v4
        with:
          name: executable-linux
          path: electron/dist/*.AppImage
