name: Build Release
on:
  workflow_dispatch:
  push:
    tags:
      - '*'
    branches:
      - release # temp for testing

jobs:
  release-draft:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    outputs:
      tag: ${{ steps.tag.outputs.tag }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
        if: github.event_name != 'push'
      - name: Set tag name
        id: tag
        run: |
          if [[ "${{ github.event_name }}" != "push" ]]; then
            tag=v$(date +%Y%m%d.%H%M%S)
          else
            tag=$(basename "${{ github.ref }}")
          fi
          tag="test-release"
          echo "tag=$tag" >> $GITHUB_OUTPUT
      - name: Create Release
        env:
          GH_TOKEN: ${{ github.token }}
          GH_REPO: ${{ github.repository }}
        run: |
          tag="${{ steps.tag.outputs.tag }}"
          gh release create --draft "$tag" --title "Release $tag" --notes ""

  build-linux:
    name: Build - AppImage Linux
    needs: [release-draft]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'yarn'
          cache-dependency-path: '**/yarn.lock'
      - name: Build Release Executable
        run: |
          yarn install --frozen-lockfile
          yarn --cwd=electron install --frozen-lockfile
          touch .env.local
          yarn release:electron
      - name: Find the executable path
        id: set-exec-path
        run: |
          executable=$(find ./electron/dist -name "*.AppImage" -print -quit)
          echo "executable=$executable" >> $GITHUB_OUTPUT
      - name: Upload Release Executable
        env:
          GH_TOKEN: ${{ github.token }}
          GH_REPO: ${{ github.repository }}
        run: |
          executable="${{ steps.set-exec-path.outputs.executable }}"
          gh release upload "${{ needs.release-draft.outputs.tag }}" "$executable"

  publish:
    name: Publish Release
    needs: [release-draft, build-linux]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Publish Release
        env:
          GH_TOKEN: ${{ github.token }}
          GH_REPO: ${{ github.repository }}
        run: gh release edit "${{ needs.release-draft.outputs.tag }}" --draft=false
      - uses: eregon/keep-last-n-releases@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          n: 10
          remove_tags_without_release: false
